### ISSUE TITLE
Calling two reducers from action handler

### ISSUE THREAD

**Issue by jamestowers** [viniciusdacal/redux-arc#20]
Is there a sensible way to do this? 

I'm calling an api endpoint which returns two sets of data which need to be handled by separate reducers, is there a better way to do it than to listen to the RESPONSE `action type` in both reducers?

**Comment by jamestowers** [comment]
Yes, sorry, two handlers, here's what i'm doing atm

```js
// userAction.js
import { createActions } from 'redux-arc'
import normalizeMiddlewareFactory from 'Store/middlewares/normalizeMiddleware'
import { profileBotsSchema } from 'Store/schema'

export const { creators, types } = createActions('user', {
  getBots: {
    url: 'profile/:id',
    method: 'get'
  }
})
```

```js
// userReducer.js

import { createReducers } from 'redux-arc'
import update from 'immutability-helper'

import { types } from '../actions/userActions'

const INITIAL_STATE = {
  bots: {
    loading: false,
    ids: []
  }
}

const requestBots = state => update(state, {
  bots: {
    loading: { $set: true }
  }
})

const receiveBots = (state, action) => {
  const { profile } = action.payload.entities
  return update(state, {
    bots: {
      loading: { $set: false },
      ids: { $set: profile.bots }
    }
  })
}


const HANDLERS = {
  [types.GET_BOTS.REQUEST]: requestBots,
  [types.GET_BOTS.RESPONSE]: receiveBots,
}

export default createReducers(INITIAL_STATE, HANDLERS)
```

```js
//botsReducer.js
import { createReducers } from 'redux-arc'
import update from 'immutability-helper'

import { types as userActionTypes } from '../actions/userActions'

const INITIAL_STATE = {
  loading: false,
  entities: [],
  categories: {}
}

const requestBots = state => update(state, {
  loading: { $set: true }
})

const receiveBots = (state, action) => {
  const { bots } = action.payload.entities
  return update(state, {
    oading: { $set: false },
    entities: { $merge: bots }
  })
}


const HANDLERS = {
  [userActionTypes.GET_BOTS.RESPONSE]: receiveBots,
}

export default createReducers(INITIAL_STATE, HANDLERS)
```

**Comment by jamestowers** [comment]
Looking at that i guess it would make more sense to import `receiveBots` from `botsReducer.js` and do this from `userReducer.js`:

```js
import { receiveBots as receiveBotsFromBotsReducer } from './botsReducer'
...
const HANDLERS = {
  [types.GET_BOTS.REQUEST]: requestBots,
  [types.GET_BOTS.RESPONSE]: receiveBots,
  [types.GET_BOTS.RESPONSE]: receiveBotsFromBotsReducer,
}
``

**Comment by viniciusdacal** [comment]
You couldn't do that, because javascript objects don't accept two keys with the same value.
What would happen, is that the second definition would override the first, then only receiveBotsFromBotsReducer would be called when you get the action `GET_BOTS_RESPONSE` dispatched.

Additionally, your redux tree would not mount the way you are expecting, if you import the `botsReducer` to use in `userReducer`, all the data that you plan to keep under `store.bots`, would now be in `store.user`

I see the actions as events that happened in the application, as a user interaction or an IO event, and the reducers are responsible to tell whether an action change or not a branch. If two different branches in the store tree should be updated when you get an action `GET_BOTS_RESPONSE`, there's no problem having two different reducers listening to it.

ps: Perhaps the function `createReducers` (from Arc) should be renamed to `createReducer`, since it generates only one reducer, using multiple handlers, could help avoiding confusions about reducers vs handlers.

**Comment by jamestowers** [comment]
>  javascript objects don't accept two keys with the same value
Of course, silly me... 🙄

Having two reducers listening to one action is working well for me

> Perhaps the function createReducers (from Arc) should be renamed to createReducer

I thinks that makes sense, `createReducers` sounds more like it will do something similar to redux's `combineReducers`
